title: Anilogia Anime DB
name: Anilogia Anime DB
email: support@anilogia.com
description: > # this means to ignore newlines until "baseurl:"
  約100年に渡るアニメ作品リストデータベース
baseurl: /animedb
url: 'https://anilogia.github.io'
markdown: kramdown
assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - node_modules/
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
exclude:
  - bin/*
  - package.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - vendor
ga_analytics: 'UA-90310463-1'
gems:
  - jekyll-assets
  - jekyll-sitemap
